[phases.setup]
nixPkgs = [
	'php83',
	'php83Packages.composer',
	'php83Extensions.curl',
	'php83Extensions.mbstring',
	'php83Extensions.zip',
	'php83Extensions.pdo',
	'php83Extensions.pdo_mysql',
	'php83Extensions.pdo_pgsql',
	'php83Extensions.pgsql',
	'php83Extensions.gd',
	'php83Extensions.fileinfo',
	'php83Extensions.tokenizer'
]

[phases.install]
cmds = ['COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader --no-scripts']

[phases.build]
cmds = [
	'mkdir -p bootstrap/cache storage/framework/cache/data storage/framework/sessions storage/framework/views storage/logs storage/app/public'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
